## Numpy array opreations

In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Basic slicing",arr[2:7])
print("With step",arr[1:8:2])
print("negative indexing",arr[-3])

Basic slicing [3 4 5 6 7]
With step [2 4 6 8]
negative indexing 8


In [4]:
arr_2D = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
print("Specific Element",arr_2D[2,2])
print("Entire row",arr_2D[1])
print("Entire row",arr_2D[:,1])


Specific Element 9
Entire row [4 5 6]
Entire row [2 5 8]


## shorting 

In [5]:
unshorted = np.array([1,3,2,4,6,3,5,9])
print("Shorted array",np.sort(unshorted))

arr_2D_unsorted = np.array([[3,1],[4,2],[6,3]])
print("shorted 2d array by column  \n",np.sort(arr_2D_unsorted,axis=1))
# axis = 1 will short array in column and axis = 0 will short array in row wise

Shorted array [1 2 3 3 4 5 6 9]
shorted 2d array by column  
 [[1 3]
 [2 4]
 [3 6]]


## Filter array

In [6]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 ==0]
print("even numbers is :",even_numbers)

even numbers is : [ 2  4  6  8 10]


## Filtrs with marks 

In [7]:
marks = numbers > 5
print("the marks greater than 5 :",numbers[marks])

the marks greater than 5 : [ 6  7  8  9 10]


## Fancy indexing vs np.where

In [8]:
indices = [0,2,4]
print(numbers[indices])

where_result = np.where(numbers>5)
print(numbers[where_result])

[1 3 5]
[ 6  7  8  9 10]


## adding and removing data

In [9]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

combined_1 = arr_1 + arr_2 # this is not the way to conbine the array this is the way too add the two array
print(combined_1)

combined_2 = np.concatenate((arr_1, arr_2))
print(combined_2)

[5 7 9]
[1 2 3 4 5 6]


## Array compatbilty shapes

In [10]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9])

print("compatbilty shapes ", a.shape == b.shape == c.shape)#checks the array is same or not the same element in the array

compatbilty shapes  True


In [13]:
original = np.array([[1,2],[3,4]])
new_row = np.array([[5,6]])

with_new_row = np.vstack((original,new_row))
print(original)
print(with_new_row)

new_col = np.array([[5],[8]])
with_new_col = np.hstack((original , new_col))
print("with new column", with_new_col)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
with new column [[1 2 5]
 [3 4 8]]


In [14]:
arr = np.array([1,2,3,4,5,6,7])
delete = np.delete(arr , 3)
print("the array is :",arr)
print("the array after deletion :",delete)


the array is : [1 2 3 4 5 6 7]
the array after deletion : [1 2 3 5 6 7]
