## Numpy array and basics 
learn about numpy with chai and code

In [1]:
import numpy as np

print(np.__version__)

2.4.6


### creating arrays from list

In [2]:
arr_1d = np.array([1,2,3,4,5])
print("1d array: ",arr_1d)

arr_2d = np.array([[1,2,3],[4,5,6]])
print("2d array: ",arr_2d)

1d array:  [1 2 3 4 5]
2d array:  [[1 2 3]
 [4 5 6]]


### list vs numpy array

In [3]:
py_list = [1,2,3,4]
print("\n ptyhon list multiplication",py_list*2)

import numpy as np
np_array = np.array([1,3,4])#element wise multiplication
print("python multiplaction :", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(100000)]
print("\n List opreation time: ", time.time() - start)

start = time.time()
np.array = np.arange(100000)*2
print("\n Numpy opreation time: ", time.time() - start)


 ptyhon list multiplication [1, 2, 3, 4, 1, 2, 3, 4]
python multiplaction : [2 6 8]

 List opreation time:  0.00751495361328125

 Numpy opreation time:  0.0


### creating array from scratch

In [1]:
import numpy as np
zeros = np.zeros((3,4)) # it will print 3x4 matrices only 0 will print
print("zeros in array:\n",zeros)

ones = np.ones((3,5))# it will only print 1 in the 3x5 matrix    
print("ones in array:\n",ones)

full = np.full((2,3), 7)
print("full array which contain only 7 :\n", full)

random = np.random.random((2,2))
print("the random in array:\n", random)

sequence = np.arange(0,10)
print("the sequence array is:\n",sequence)

zeros in array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones in array:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
full array which contain only 7 :
 [[7 7 7]
 [7 7 7]]
the random in array:
 [[0.67713901 0.75783452]
 [0.41330099 0.86154232]]
the sequence array is:
 [0 1 2 3 4 5 6 7 8 9]


### vector , matrix and tensor 

In [ ]:
vector = np.array([1,2,3])
print("the vector is:",vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print("matrix is:",matrix)

tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor is:\n", tensor)

### Array Properties

In [ ]:
array = np.array([[2,3,4],
                  [4,5,6]])
print("shape:",array.shape)
print("size:",array.size)
print("data type:",array.dtype)
print("dimenson:",array.ndim)

### Array Reshaping

In [2]:
import numpy as np
arr = np.arange(12)
print("Original array:",arr)

reshape = arr.reshape((3,4))
print("reshaped array:",reshape)

# flattened copy the original array
flattened = reshape.flatten()
print("the falttened array is:",flattened)

#reveled view instead of copy
reveled = flattened.ravel()
print("the reveled array is:",reveled)

transposed = reshape.T
print("the reshaaped array is:",transposed)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
reshaped array: [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
the falttened array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]
the reveled array is: [ 0  1  2  3  4  5  6  7  8  9 10 11]
the reshaaped array is: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
